#!/usr/bin/expect --

# Version 08/14/12
#
# Author: Justin Ryburn (justin@ryburn.org)
# This script performs a remote login to MX2-Qfabric-R182 in the Juniper Herndon POC lab.
#
# Usage: MX2-Qfabric-R182
#

set user jryburn
set pass KyD8FN7W
set host 172.25.52.182
set timeout 30

spawn -noecho telnet $host
   expect -re "login*"
   send "$user\r"
   expect -re "Password:*"
   send "$pass\r"
interact
