#!/usr/bin/expect --

# Version 08/14/12
#
# Author: Justin Ryburn (justin@ryburn.org)
# This script performs a remote login to MX80-87 in the Juniper Herndon POC lab.
#
# Usage: MX80-87
#

set user jryburn
set pass pL9kJx2w
set host 172.25.46.87
set timeout 30

spawn -noecho telnet $host
   expect -re "login*"
   send "$user\r"
   expect -re "Password:*"
   send "$pass\r"
interact
